"""Current NIFTY Smallcap 250 constituent list (NSE symbols), fetched from
NSE's official archive CSV
(https://archives.nseindia.com/content/indices/ind_niftysmallcap250list.csv)
on 2026-08-24. Used by backtest15.py for the "Smallcap250 Momentum 20/10"
custom reconstructions — no pure-momentum NSE index exists for smallcaps;
the real one is Nifty Smallcap250 Momentum Quality 100 (a momentum+quality
HYBRID score, top 100, capped 3%) — a different formula. This project
applies the plain momentum-only formula used throughout this series instead,
consistent with every other momentum reconstruction here.
"""

NIFTY_SMALLCAP250_SYMBOLS = [
    "ACMESOLAR","AADHARHFC","AARTIIND","AAVAS","ACE","ACUTAAS","ABFRL","ABLBL","ABREL","ABSLAMC",
    "CPPLUS","AEGISLOG","AEGISVOPAK","AFCONS","AFFLE","ABDL","ARE&M","AMBER","ANANDRATHI","ANANTRAJ",
    "ANGELONE","ANURAS","APTUS","ASAHIINDIA","ASTERDM","ATHERENERG","ATUL","BEML","BLS","BALRAMCHIN",
    "BANDHANBNK","BATAINDIA","BAYERCROP","BELRISE","BIKAJI","BSOFT","BLUEDART","BLUEJET","BBTC",
    "FIRSTCRY","BRIGADE","MAPMYINDIA","CCL","CESC","CIEINDIA","CANFINHOME","CANHLIFE","CAPLIPOINT",
    "CGCL","CARBORUNIV","CARTRADE","CASTROLIND","CEATLTD","CEMPRO","CENTRALBK","CDSL","CHALET",
    "CHAMBLFERT","CHENNPETRO","CHOICEIN","CHOLAHLDNG","CUB","CLEAN","COHANCE","CAMS","CONCORDBIO",
    "CRAFTSMAN","CREDITACC","CROMPTON","CYIENT","DCMSHRIRAM","DOMS","DATAPATTNS","DEEPAKFERT",
    "DEEPAKNTR","DELHIVERY","DEVYANI","LALPATHLAB","EIDPARRY","EIHOTEL","ELECON","ELGIEQUIP","EMAMILTD",
    "EMCURE","EMMVEE","ENGINERSIN","ERIS","FACT","FINCABLES","FSL","FIVESTAR","FORCEMOT","GABRIEL",
    "GALLANTT","GRSE","GILLETTE","GLAND","GODIGIT","GPIL","GRANULES","GRAPHITE","GRAVITA","GESHIP",
    "GMDCLTD","HEG","HBLENGINE","HFCL","HSCL","HINDCOPPER","HOMEFIRST","HONASA","IDBI","IFCI","IIFL",
    "IRB","IRCON","ITI","INDGN","INDIACEM","INDIAMART","IEX","IOB","IGL","INOXWIND","INTELLECT","IGIL",
    "IKS","JBMA","JKTYRE","JMFINANCIL","JSWCEMENT","JSWDULUX","JAINREC","JPPOWER","J&KBANK","JINDALSAW",
    "JUBLINGREA","JUBLPHARMA","JWL","JYOTICNC","KAJARIACER","KPIL","KARURVYSYA","KAYNES","KEC",
    "KFINTECH","KIRLOSENG","KIMS","LTFOODS","LATENTVIEW","THELEELA","LEMONTREE","MMTC","MGL",
    "MANAPPURAM","MRPL","MEESHO","MINDACORP","MSUMI","NATCOPHARM","NBCC","NCC","NSLNISP","NH","NAVA",
    "NAVINFLUOR","NETWEB","NEULANDLAB","NEWGEN","NIVABUPA","NUVAMA","NUVOCO","OLAELEC","OLECTRA",
    "ONESOURCE","PCBL","PGEL","PNBHOUSING","PTCIL","PVRINOX","PARADEEP","PFIZER","PWL","PINELABS",
    "PIRAMALFIN","PPLPHARMA","POLYMED","POONAWALLA","PFOCUS","RRKABEL","RBLBANK","RHIM","RITES",
    "RAILTEL","RAINBOW","RKFORGE","REDINGTON","RPOWER","SBFC","SAGILITY","SAILIFE","SAMMAANCAP",
    "SAPPHIRE","SARDAEN","SAREGAMA","SCHNEIDER","SCI","SHYAMMETL","SIGNATURE","SOBHA","SONACOMS",
    "SONATSOFTW","STARHEALTH","SUMICHEM","SUNTV","SPLPETRO","SWANCORP","SYNGENE","SYRMA","TBOTEK",
    "TATACHEM","TATATECH","TTML","TECHNOE","TEGA","TEJASNET","TENNIND","RAMCOCEM","TIMKEN","TITAGARH",
    "TARIL","TRAVELFOOD","TRIDENT","TRITURBINE","UCOBANK","UTIAMC","URBANCO","USHAMART","VTL","VIJAYA",
    "WELCORP","WELSPUNLIV","WHIRLPOOL","WOCKPHARMA","ZFCVINDIA","ZEEL","ZENTEC","ZENSARTECH","ZYDUSWELL",
    "ECLERX",
]
