"""Current NIFTY Midcap 150 constituent list (NSE symbols), fetched from
NSE's official archive CSV
(https://archives.nseindia.com/content/indices/ind_niftymidcap150list.csv)
on 2026-08-24. Used by backtest13.py for the "Midcap150 Momentum 20" custom
reconstruction — see that file's docstring: the real NSE index is Nifty
Midcap150 Momentum 50 (top 50, not top 20) — no official "Momentum 20"
variant exists, same situation as the NIFTY100 Momentum 10 case.
"""

NIFTY_MIDCAP150_SYMBOLS = [
    "360ONE","3MINDIA","ACC","AIAENG","APLAPOLLO","AUBANK","AWL","ABBOTINDIA","ATGL","ABCAPITAL",
    "AJANTPHARM","ALKEM","ANTHEM","APARINDS","APOLLOTYRE","ASHOKLEY","ASTRAL","AUROPHARMA","AIIL","BSE",
    "BAJAJHFL","BALKRISIND","BANKINDIA","MAHABANK","BERGEPAINT","BDL","BHARATFORG","BHEL","BHARTIHEXA",
    "GROWW","BIOCON","BLUESTARCO","CRISIL","COCHINSHIP","COFORGE","COLPAL","CONCOR","COROMANDEL","DABUR",
    "DALBHARAT","DIXON","ENDURANCE","ESCORTS","EXIDEIND","NYKAA","FEDERALBNK","FORTIS","GVT&D",
    "GMRAIRPORT","GICRE","GLAXO","GLENMARK","MEDANTA","GODFRYPHLP","GODREJIND","GODREJPROP","FLUOROCHEM",
    "HDBFS","HAVELLS","HEROMOTOCO","HEXT","HINDPETRO","POWERINDIA","HONAUT","HUDCO","ICICIGI","ICICIAMC",
    "ICICIPRULI","IDFCFIRSTB","ITCHOTELS","INDIANB","IRCTC","IREDA","INDUSTOWER","INDUSINDBK","NAUKRI",
    "IPCALAB","JKCEMENT","JSWENERGY","JSWINFRA","JSL","JUBLFOOD","KPRMILL","KEI","KPITTECH","KALYANKJIL",
    "LTF","LTTS","LGEINDIA","LICHSGFIN","LAURUSLABS","LENSKART","LICI","LINDEINDIA","LLOYDSME","LUPIN",
    "MRF","M&MFIN","MANKIND","MARICO","MFSL","MOTILALOFS","MPHASIS","MCX","NHPC","NLCINDIA","NMDC",
    "NTPCGREEN","NATIONALUM","NAM-INDIA","OBEROIRLTY","OIL","PAYTM","OFSS","POLICYBZR","PIIND","PAGEIND",
    "PATANJALI","PERSISTENT","PETRONET","PHOENIXLTD","POLYCAB","PREMIERENE","PRESTIGE","RADICO","RVNL",
    "SBICARD","SJVN","SRF","SCHAEFFLER","SAIL","SUNDARMFIN","SUPREMEIND","SUZLON","SWIGGY","TATACOMM",
    "TATAELXSI","TATAINVEST","NIACL","THERMAX","TORNTPOWER","TIINDIA","UNOMINDA","UPL","UBL","VMM","IDEA",
    "VOLTAS","WAAREEENER","YESBANK",
]
